a=10
print("type of a=10 is",type(a))
a=10.45
print("type of a=10.45 is",type (a))
a="sandip"
print("type of a=sandip is",type(a))
a=[10,20,30.4]
print("type of a=",type(a))
a={1,2,3}
print("type of a=",type(a))
a=False
print("type of a=",type(a))
a={"roll":53,"name":"SANDIP"}
print("type of a=",type(a))
