a=int(input('enter a no'))
print(a)
print("type of a = ",type(a))
a=float(input("enter a no"))
print(a)
print("type of a = ",type(a))
a=str(input("enter a string"))
print(a)
print("type of a = ",type(a))

